version: "3"
services:
  app:
    # For Debug
    stdin_open: true
    tty: true
    restart: always
    build: .
    command: bash init.sh
    networks:
      - db_network
      - app_network
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
    networks:
      - db_network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=blog
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci

  web:
    image: nginx
    restart: always
    networks:
      - app_network
    depends_on:
      - app
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/mime.types:/etc/nginx/mime.types:ro
      - .:/app
    ports:
      - "8081:80"

networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge
volumes:
  dbdata:
